# Generated by Django 3.0.8 on 2020-07-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='note',
            name='contacts',
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
            preserve_default=False,
        ),
    ]
